### ISSUE TITLE
`pip install urwidtrees` fails if `urwid` isn't installed yet

### ISSUE THREAD

**Issue by bwesterb** [pazz/urwidtrees#22]
```
$ virtualenv-2.7 test
New python executable in test/bin/python
Installing setuptools, pip, wheel...done.
$ source test/bin/activate
(test) $ pip install urwidtrees
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting urwidtrees
  Downloading urwidtrees-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/pm/10pl16cj2mldkky06201p_7w0000gn/T/pip-build-pMpY4h/urwidtrees/setup.py", line 4, in <module>
        import urwidtrees
      File "urwidtrees/__init__.py", line 11, in <module>
        from .decoration import DecoratedTree, CollapsibleTree
      File "urwidtrees/decoration.py", line 4, in <module>
        import urwid
    ImportError: No module named urwid
```

I am working on a fix.

**Comment by TomasTomecek** [comment]
Same here.

```python
import urwidtrees
```

https://github.com/pazz/urwidtrees/blob/master/setup.py#L4

This is really really bad. To me it doesn't make sense to use a package which you are actually installing.

**Comment by bwesterb** [comment]
Should already be fixed in `pip`.

**Comment by bwesterb** [comment]
```
bas@bohr ~/tmp $ virtualenv-2.7 test
New python executable in test/bin/python
Installing setuptools, pip, wheel...done.
bas@bohr ~/tmp $ source test/bin/activate
(test)bas@bohr ~/tmp $ pip install urwidtrees
Collecting urwidtrees
  Downloading urwidtrees-1.0.1.1.tar.gz
Building wheels for collected packages: urwidtrees
  Running setup.py bdist_wheel for urwidtrees
  Stored in directory: /Users/bas/Library/Caches/pip/wheels/e0/1c/7c/b672e433dc88d50c42ec25741a013f6743fb0b0a07e49b3e07
Successfully built urwidtrees
Installing collected packages: urwidtrees
Successfully installed urwidtrees-1.0.1.1
```
